// apps/extension/entries/entries.js
const TRIBAL_WARS_MATCHES = [
  'https://*.tribalwars.com.br/*',
  'https://*.die-staemme.de/*',
  'https://*.staemme.ch/*',
  'https://*.tribalwars.net/*',
  'https://*.tribalwars.nl/*',
  'https://*.plemiona.pl/*',
  'https://*.tribalwars.com.pt/*',
  'https://*.divokekmeny.cz/*',
  'https://*.triburile.ro/*',
  'https://*.voynaplemyon.com/*',
  'https://*.fyletikesmaxes.gr/*',
  'https://*.divoke-kmene.sk/*',
  'https://*.klanhaboru.hu/*',
  'https://*.tribals.it/*',
  'https://*.klanlar.org/*',
  'https://*.guerretribale.fr/*',
  'https://*.guerrastribales.es/*',
  'https://*.tribalwars.ae/*',
  'https://*.tribalwars.co.uk/*',
  'https://*.tribalwars.works/*',
  'https://*.tribalwars.us/*',
  'https://*.tribalwars.cash/*',
]

const DEFAULT_EXCLUDE_MATCHES = [
  'https://*.google.com/*',
  'https://*/create_village.php?/*',
  '*://extensions/*',
]

module.exports = {
  sw: {
    'service-worker/index': {
      entry: 'service-worker/index.ts',
      type: 'service-worker',
      target: 'webworker',
    },
  },

  pg: {
    popup: {
      entry: 'pages/popup/index.tsx',
      type: 'popup',
      target: 'web',
      htmlFilename: 'popup.html',
      title: "Let's GO! - Player Assistant",
    },
  },

  csVanilla: {
    'traking': {
      entry: 'content-scripts/vanilla/main/top/start/traking/index.js',
      matches: TRIBAL_WARS_MATCHES,
      excludeMatches: DEFAULT_EXCLUDE_MATCHES,
      world: 'MAIN',
      injection: 'vanilla',
      scope: 'top',
      runAt: 'document_start',
      allFrames: false,
      target: 'web',
    },    
    'globalChange': {
      entry: 'content-scripts/vanilla/main/top/start/globalChange/index.ts',
      matches: TRIBAL_WARS_MATCHES,
      excludeMatches: DEFAULT_EXCLUDE_MATCHES,
      world: 'MAIN',
      injection: 'vanilla',
      scope: 'top',
      runAt: 'document_start',
      allFrames: false,
      target: 'web',
    },
    'starter': {
      entry: 'content-scripts/vanilla/main/top/start/starter/index.ts',
      matches: TRIBAL_WARS_MATCHES,
      excludeMatches: DEFAULT_EXCLUDE_MATCHES,
      world: 'MAIN',
      injection: 'vanilla',
      scope: 'top',
      runAt: 'document_start',
      allFrames: false,
      target: 'web',
      build: {
        profile: 'starter',
        obfuscationLevel: 'medium',
      },
    },    
    'clock': {
      entry: 'content-scripts/vanilla/main/top/start/clock/index.js',
      matches: TRIBAL_WARS_MATCHES,
      excludeMatches: DEFAULT_EXCLUDE_MATCHES,
      world: 'MAIN',
      injection: 'vanilla',
      scope: 'top',
      runAt: 'document_start',
      allFrames: false,
      target: 'web',
    },
    'connect': {
      entry: 'content-scripts/vanilla/isolated/all-frames/start/connect/index.ts',
      matches: TRIBAL_WARS_MATCHES,
      excludeMatches: DEFAULT_EXCLUDE_MATCHES,
      world: 'ISOLATED',
      injection: 'vanilla',
      scope: 'all-frames',
      runAt: 'document_start',
      allFrames: true,
      target: 'web',
    },
    'support': {
      entry: 'content-scripts/vanilla/isolated/top/idle/support/index.ts',
      matches: TRIBAL_WARS_MATCHES,
      excludeMatches: DEFAULT_EXCLUDE_MATCHES,
      world: 'ISOLATED',
      injection: 'vanilla',
      scope: 'top',
      runAt: 'document_idle',
      allFrames: false,
      target: 'web',
      build: {
        profile: 'support',
        obfuscationLevel: 'lowCompact',
      },
    },
    'incomingWatch': {
      entry: 'content-scripts/vanilla/isolated/top/idle/incomingWatch/index.ts',
      matches: TRIBAL_WARS_MATCHES,
      excludeMatches: DEFAULT_EXCLUDE_MATCHES,
      world: 'ISOLATED',
      injection: 'vanilla',
      scope: 'top',
      runAt: 'document_idle',
      allFrames: false,
      target: 'web',
      build: {
        profile: 'incoming-watch',
        obfuscationLevel: 'lowCompact',
      },
    },
    'worldDatabaseApi': {
      entry: 'content-scripts/vanilla/isolated/all-frames/idle/worldDatabaseApi/index.js',
      matches: TRIBAL_WARS_MATCHES,
      excludeMatches: DEFAULT_EXCLUDE_MATCHES,
      world: 'ISOLATED',
      injection: 'vanilla',
      scope: 'all-frames',
      runAt: 'document_idle',
      allFrames: true,
      target: 'web',
      build: {
        profile: 'world-database-api',
        obfuscationLevel: 'low',
      },
    },
    'groupIntentSync': {
      entry: 'content-scripts/vanilla/isolated/all-frames/idle/groupIntentSync/index.js',
      matches: TRIBAL_WARS_MATCHES,
      excludeMatches: DEFAULT_EXCLUDE_MATCHES,
      world: 'ISOLATED',
      injection: 'vanilla',
      scope: 'all-frames',
      runAt: 'document_idle',
      allFrames: true,
      target: 'web',
      build: {
        profile: 'group-intent-sync',
        obfuscationLevel: 'lowCompact',
      },
    },
    'solver': {
      entry: 'content-scripts/vanilla/isolated/all-frames/idle/solver/index.js',
      matches: ["https://*.hcaptcha.com/*"],
      world: 'ISOLATED',
      injection: 'vanilla',
      scope: 'all-frames',
      runAt: 'document_idle',
      allFrames: true,
      target: 'web',
    },
  },

  csAssetVanilla: {
    'game.prepared': {
      entry: 'content-scripts/vanilla/main/top/asset/prepared/index.js',
      filename: 'game.prepared.js',
      exposeMatches: 'externally_connectable',
      build: {
        profile: 'prepared-asset',
        obfuscationLevel: 'lowCompact',
      },
    },
  },

  csShadowDom: {
    // 'content-scripts/shadowdom/isolated.top.start': {
    //   entry: 'content-script/isolated/top/start/index.js',
    //   matches: TRIBAL_WARS_MATCHES,
    //   excludeMatches: DEFAULT_EXCLUDE_MATCHES,
    //   world: 'ISOLATED',
    //   injection: 'shadowdom',
    //   scope: 'top',
    //   runAt: 'document_start',
    //   allFrames: false,
    //   target: 'web',
    // },
  },
}
