export const SUPPORT_GET_POPUP_STATE_MESSAGE_TYPE = 'SUPPORT_GET_POPUP_STATE'
export const SUPPORT_LOGOUT_MESSAGE_TYPE = 'SUPPORT_LOGOUT'
export const SUPPORT_PROBE_MESSAGE_TYPE = 'SUPPORT_PROBE'
export const SUPPORT_SYNC_PLAYER_AVATAR_MESSAGE_TYPE = 'SUPPORT_SYNC_PLAYER_AVATAR'
